# Generated by Django 4.2.16 on 2024-12-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surf_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='session_type',
            field=models.CharField(default='Beginner', max_length=100),
        ),
    ]
